# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25dabe22bbe7d95da7cc4c248887d2a54b8bc36e887d06d5f1a523400ea919bca5909a0d653ab14b90a1ad0b22b58a068afd0f09341005a5d66583fc3ea94c4

test:
  secret_key_base: 3259034a3b1c0401b6c155b799629b641b8fbfbf6dd01a1a7b29f42f3311e7d03ace7795fa04163f98500a6da2a429a7a37306fe546247ad7b03e49e7f173a54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
